name: FastAPI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  Semver:
    runs-on: ubuntu-latest
    container: marcelocorreia/semver
    permissions:
      contents: read
    if: github.ref == 'refs/heads/master'
    outputs:
      patched: ${{ steps.bump.outputs.patched }}
    steps:
      - uses: actions/checkout@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Version bump
        id: bump
        run: |
          CURRENT=$(git tag -l --sort=-v:refname)
          PATCHED=$(semver -c -i patch $CURRENT)
          echo "patched=$PATCHED" >> "$GITHUB_OUTPUT"

      - name: Git tags
        id: bump
        env:
          PATCHED: ${{ steps.bump.outputs.patched }}
        run: |
          git tag $PATCHED
          git push --tags

  DockerBuild:
    runs-on: ubuntu-latest
    needs:
      - Semver
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: docker build -f Dockerfile -t ghcr.io/${{ github.repository_owner }}/fastapi:${{ github.sha }} .
        if: github.event_name == 'push'

      - name: Docker login
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        if: github.event_name == 'push'

      - name: Push sha
        run: docker push ghcr.io/${{ github.repository_owner }}/fastapi:${{ github.sha }}
        if: github.event_name == 'push'

      - name: Push semver
        env:
          PATCHED: ${{ needs.Semver.outputs.patched }}
        run: |
          docker tag ghcr.io/${{ github.repository_owner }}/fastapi:${{ github.sha }} ghcr.io/${{ github.repository_owner }}/fastapi:$PATCHED
          docker push ghcr.io/${{ github.repository_owner }}/fastapi:$PATCHED
        if: ${{ (github.event_name == 'push') && (github.ref == 'refs/heads/master') }}

  Tests:
    runs-on: ubuntu-latest
    needs:
      - DockerBuild
    container:
      image: ghcr.io/${{ github.repository_owner }}/fastapi:${{ github.sha }}
      options: --entrypoint ""
    steps:
      - uses: actions/checkout@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Dependencies
        run: |
          python3 -m venv venv
          . venv/bin/activate
          pip install -r requirements.txt

      - name: Tests
        run: |
          . venv/bin/activate
          pytest test/test.py

  # TODO set chart version
  HelmRelease:
    runs-on: ubuntu-latest
    needs:
      - Semver
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        with:
          charts_dir: charts
        env:
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
